# file Checked
# Checked
#' @name addINFO
#' @title Summary hap results
#' @description add annotations to `INFO` fields used for `plotHapTable()`
#' @usage
#' addINFO(hapResult,
#'         tag = "", values = values,
#'         replace = FALSE, sep = ";")
#' @examples
#' \dontrun{
#' data("geneHap_test")
#' hap <- vcf2hap(vcf)
#'
#' # length of values must be equal with number of sites in hap result
#' values <- paste0("newInfo",c(1:9))
#' hap <- addINFO(hap, tag = "new", values = values, replace = TRUE)
#' }
#' @seealso
#' \code{\link[geneHapR:plotHapTable]{plotHapTable()}}
#' @param hapResult object of `hapResult` class generated by `vcf2hap()` or `seqs2hap` or `import_hap()`;
#' or object of `hapSummary` class generated by `hap_summary()`
#' @param tag tag names. Usually is a single word used before "="
#' @param values annotation for each site.
#' Length of values must be equal with sites in hap result
#' @param replace whether replace origin INFOs in hap result or not.
#' Default as FALSE
#' @inheritParams base::paste
addINFO <- function(hapResult,
                    tag = "",
                    values = values,
                    replace = FALSE,
                    sep = ";") {
    # get POS in hapResult
    POS <- t(hapResult[hapResult$Hap == "POS", ])[, 1]
    POS <- suppressWarnings(as.numeric(names(POS)))
    probe <- !is.na(POS)
    POS <- POS[probe]
    if (length(values) != length(POS))
        stop("Length of 'values' should be equal with sites")

    # set tag_value pairs
    values <- paste0(tag, "=", values)

    if (replace) {
        INFO <- values
    } else {
        # get INFO in hapResult
        INFO <- t(hapResult[hapResult$Hap == "INFO", ])[, 1]
        INFO <- INFO[probe]
        INFO[is.na(INFO)] <- ""

        # set INFOs
        for (i in seq_len(length(INFO))) {
            if (nchar(INFO[i]) == 0) {
                INFO[i] <- values[i]
            } else {
                INFO[i] <- paste(INFO[i], values[i], sep = sep)
            }
        }
    }

    n <- ncol(hapResult) - length(INFO) - 1
    hapResult[hapResult$Hap == "INFO", ] <-
        c("INFO", INFO, rep("", n))
    return(hapResult)
}
